spring.application.name=transfer-tracker

football.api.base-url=https://v3.football.api-sports.io
football.api.key=${API_FOOTBALL_KEY}

x.api.base-url=https://api.x.com
x.api.bearer-token=${X_API_BEARER_TOKEN}

spring.jpa.properties.hibernate.format_sql=true

admin.username=${ADMIN_USERNAME}
admin.password=${ADMIN_PASSWORD}