spring.application.name=transfer-tracker

spring.profiles.active=local

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# ???? SQL ??
logging.level.org.hibernate.SQL=DEBUG

# ? ? ???? ?? ??? ? ??
logging.level.org.hibernate.orm.jdbc.bind=TRACE